server:
  port: 8011
spring:
  application:
    name: gcuforum
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    encoding: UTF-8
    prefix: classpath:/static
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 5
    timeout: 3000
    port: 6379
  web:
    resources:
      static-locations: classpath:/static


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl